### PR TITLE
Add README to WildFly-Discovery

### PR DESCRIPTION
**Pull request by sudeshnas93**
Issue: https://issues.redhat.com/browse/WFDISC-43

### CODE REVIEW

**Comment by sudeshnas93** [comment]
Hello @dmlloyd, Could you please review and provide your feedback so as to add some more information, if required.

**Review by dmlloyd — APPROVED** [review]
LGTM

**Comment by sudeshnas93** [comment]
Thank you. :)

**Comment by sudeshnas93** [comment]
Hello @tadamski , could you please review and merge this PR?

**Review by tadamski — APPROVED** [review]

**Pull request merged**
