### PR TITLE
WFDISC-29 Allow traversal of all attributes of a ServiceURL.

### PR DESCRIPTION
**Pull request by pferraro**

### CODE REVIEW

**Comment by pferraro** [comment]
@dmlloyd Any objections?

**Comment by dmlloyd** [comment]
In principle, it looks fine, but I'd like to see the set cached on a field so that it's not re-created each time.

**Comment by dmlloyd** [comment]
Alternatively, the map could just be wrapped in an unmodifiable map on create().

**Comment by dmlloyd** [comment]
Also this should be associated with a WFDISC JIRA please.

**Comment by pferraro** [comment]
@dmlloyd Done.

**Comment by pferraro** [comment]
"Alternatively, the map could just be wrapped in an unmodifiable map on create()."
I opted not to do that, as this would alter the serialization format.

**Pull request merged**
